# Generated by Django 6.0.4 on 2026-04-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='files/')),
                ('extension', models.CharField(choices=[('VIDEO', 'Видео'), ('IMAGE', 'Картинка'), ('TXT', 'Текст'), ('PDF', 'pdf'), ('WORD', 'Word'), ('EXCEL', 'Excel'), ('OTHER', 'Другое')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
