# Generated by Django 6.0.4 on 2026-04-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
