# Generated by Django 6.0.4 on 2026-04-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('FULLADMIN', 'Гл.Админ'), ('ADMIN', 'Админ'), ('USER', 'Пользователь'), ('VIEWER', 'Наблюдатель')], default='VIEWER'),
        ),
    ]
