# Generated by Django 6.0.4 on 2026-04-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_fileforusermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='extension',
            field=models.CharField(choices=[('VIDEO', 'Видео'), ('IMAGE', 'Картинка'), ('TXT', 'Текст'), ('PDF', 'pdf'), ('WORD', 'Word'), ('EXCEL', 'Excel'), ('ARCHIVE', 'Архив'), ('OTHER', 'Другое')], max_length=10),
        ),
    ]
