# Generated by Django 6.0.4 on 2026-04-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_filemodel_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='extension',
            field=models.CharField(choices=[('VIDEO', 'Видео'), ('PNG', 'png'), ('JPEG', 'jpeg'), ('WEB', 'web'), ('TXT', 'Текст'), ('PDF', 'pdf'), ('WORD', 'Word'), ('EXCEL', 'Excel'), ('ARCHIVE', 'Архив'), ('OTHER', 'Другое')], max_length=10),
        ),
    ]
