# Generated by Django 6.0.4 on 2026-04-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_filemodel_extension'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileForUserModel',
        ),
    ]
