# Generated by Django 6.0.4 on 2026-04-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_fileforusermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
    ]
