# Generated by Django 6.0.4 on 2026-04-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_customuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='extension',
            field=models.CharField(max_length=10),
        ),
    ]
